### ISSUE TITLE
Discussion about DCDGAN

### ISSUE THREAD

**Issue by tachikoma777** [cxtalk/cxtalk.github.io#2]
麻烦回答一下两个非常简单的问题，1.你代码里的CGB是不是其实只是DCLGAN的对比loss  2、H * 和 R *是在代码那个部分feed进CGB的？
我很友善地问问题，不想回答你留着问题我都ok的。
或者您推荐我发到知乎和B站讨论一下你今年的这两篇论文？or请教一下论文其他作者

**Comment by cxtalk** [comment]
您好，感到非常抱歉。以为上个issue1回复您后长时间没收到信息，以为解决了您的困惑，故出于个人习惯关闭了issue1。该工作是受DCLGAN的启发，因为DCLGAN是在CycleGAN中施加对比学习，而本工作的目标是学习一个无监督去雨模型，因此还在基础上新增适合去雨的颜色循环损失、频域损失等来优化在去雨任务上的结果。在技术层面，CGB只是为了方便文章写作而起的名称，其实和CUT/DCLGAN中的对比loss基本相同。对于feed进CGB，同CUT一样是通过编码器提取L层后到MLP等操作实现的。感谢您的关注，再次对您的问题一开始没有做出很好的回复表示真挚的抱歉，祝您工作顺利！

**Comment by tachikoma777** [comment]
> 您好，感到非常抱歉。以为上个issue1回复您后长时间没收到信息，以为解决了您的困惑，故出于个人习惯关闭了issue1。该工作是受DCLGAN的启发，因为DCLGAN是在CycleGAN中施加对比学习，而本工作的目标是学习一个无监督去雨模型，因此还在基础上新增适合去雨的颜色循环损失、频域损失等来优化在去雨任务上的结果。在技术层面，CGB只是为了方便文章写作而起的名称，其实和CUT/DCLGAN中的对比loss基本相同。对于feed进CGB，同CUT一样是通过编码器提取L层后到MLP等操作实现的。感谢您的关注，再次对您的问题一开始没有做出很好的回复表示真挚的抱歉，祝您工作顺利！

还是感谢你的回复。既然是这样，我还是觉得CUT/DCLGAN的对比loss本质在于保结构，其正负样本的选择完全出于位置对应，与论文中CGB的在两个域之间构造正负样本有所差异，如有误解欢迎讨论。

**Comment by cxtalk** [comment]
收到，非常感谢您的宝贵建议。
